apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-stable
  namespace: kube-system
spec:
  interval: 1h0m0s
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: kube-system
spec:
  interval: 1h0m0s
  chart:
    spec:
      chart: nginx-ingress
      version: ">=0.13.0"
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: kube-system
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true